namespace Lyrida.Infrastructure.Common.Enums;

/// <summary>
/// Enumeration for the application's localized strings
/// </summary>
/// <remarks>
/// Creation Date: 18th of January, 2022
/// </remarks>
public enum Terms
{
    Conflict,
    NoErrors,
    NotFound,
    Forbidden,
    BadRequest,
    NoThumbnail,
    NoFirstError,
    GetUserError,
    GetUsersError,
    InvalidUserId,
    FileCopyError,
    FileMoveError,
    TokenIsExpired,
    DeleteUserError,
    InsertUserError,
    InvalidPassword,
    InvalidTotpCode,
    InvalidUsername,
    ValidationError,
    EmptyNewPassword,
    InvalidPathError,
    IdMustBePositive,
    MaximumLength200,
    InvalidPermission,
    MaximumLength1000,
    FileNotFoundError,
    PathCannotBeEmpty,
    PasswordsNotMatch,
    ErrorUpdatingUser,
    GetUserPagesError,
    UnauthorizedAccess,
    DirectoryMoveError,
    DirectoryCopyError,
    DatabaseSetupError,
    TokenCannotBeEmpty,
    UpdateUserPageError,
    DeleteUserPageError,
    InternalServerError,
    InsertUserPageError,
    EmptyPasswordConfirm,
    EmptyCurrentPassword,
    ValueGreaterThanZero,
    CannotNavigateUpError,
    LastNameCannotBeEmpty,
    PasswordCannotBeEmpty,
    TotpCodeCannotBeEmpty,
    UsernameCannotBeEmpty,
    NameCannotBeEmptyError,
    FileAlreadyExistsError,
    DirectoryNotFoundError,
    AccountAlreadyVerified,
    DuplicateUsernameError,
    FirstNameCannotBeEmpty,
    ErrorValidatingAccount,
    GetUserPreferencesError,
    EmptyNewPasswordConfirm,
    GetUserEnvironmentsError,
    CannotDeleteAdminAccount,
    ClickHereToChangePassword,
    ErrorInitializingDatabase,
    UninitializedDatabaseError,
    InsertUserPreferencesError,
    InsertUserEnvironmentError,
    UpdateUserPreferencesError,
    UpdateUserEnvironmentError,
    DirectoryAlreadyExistsError,
    ErrorValidatingPasswordReset,
    ValueBetweenZeroAndOneHundred,
    ProfilePreferencesCannotBeEmpty,
}