namespace Lyrida.Infrastructure.Common.Enums;

/// <summary>
/// Enumeration for the application's localized strings
/// </summary>
/// <remarks>
/// Creation Date: 18th of January, 2022
/// </remarks>
public enum Terms
{
    Conflict,
    NoErrors,
    NotFound,
    Forbidden,
    BadRequest,
    NoThumbnail,
    NoFirstError,
    Unauthorized,
    GetUsersError,
    InvalidUserId,
    PasswordReset,
    TokenIsExpired,
    DeleteUserError,
    UpdateRoleError,
    InvalidPassword,
    InvalidTotpCode,
    InvalidUsername,
    ValidationError,
    ErrorGettingRole,
    EmptyNewPassword,
    InvalidPathError,
    ErrorGettingUser,
    IdMustBePositive,
    MaximumLength200,
    RoleDoesNotExist,
    RoleAlreadyExists,
    InvalidPermission,
    MaximumLength1000,
    UnverifiedAccount,
    ErrorDeletingRole,
    NameCannotBeEmpty,
    ErrorGettingRoles,
    PasswordsNotMatch,
    ErrorUpdatingUser,
    GetUserPagesError,
    DatabaseSetupError,
    CannotSetAdminRole,
    ErrorInsertingRole,
    TokenCannotBeEmpty,
    ErrorInsertingUser,
    TokenAlreadyIssued,
    EmailCannotBeEmpty,
    DeleteUserPageError,
    DuplicateEmailError,
    InvalidEmailAddress,
    InternalServerError,
    InsertUserPageError,
    EmptyPasswordConfirm,
    EmptyCurrentPassword,
    PasswordChangeEmail1,
    PasswordChangeEmail2,
    CannotNavigateUpError,
    RoleNameCannotBeEmpty,
    LastNameCannotBeEmpty,
    PasswordCannotBeEmpty,
    CannotDeleteAdminRole,
    CannotUpdateAdminRole,
    ErrorGettingUserRoles,
    ErrorUpdatingUserRole,
    TotpCodeCannotBeEmpty,
    AccountAlreadyVerified,
    FirstNameCannotBeEmpty,
    ErrorValidatingAccount,
    GetUserPreferencesError,
    RoleMustHavePermissions,
    ErrorGettingPermissions,
    EmptyNewPasswordConfirm,
    ErrorInsertingPermission,
    CannotDeleteAdminAccount,
    ClickHereToChangePassword,
    ErrorInitializingDatabase,
    UninitializedDatabaseError,
    InsertUserPreferencesError,
    UpdateUserPreferencesError,
    ErrorGettingUserPermissions,
    ErrorGettingRolePermissions,
    ErrorValidatingPasswordReset,
    ErrorUpdatingUserPermissions, 
    ValueBetweenZeroAndOneHundred,
    ProfilePreferencesCannotBeEmpty,
}